apiVersion: apps/v1
kind: Deployment
metadata:
  name: subfinder-backend
  labels:
    app: subfinder
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subfinder
      component: backend
  template:
    metadata:
      labels:
        app: subfinder
        component: backend
    spec:
      containers:
      - name: subfinder-backend
        image: ${BACKEND_IMAGE:-subfinder-backend:latest}
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: WORKER_COUNT
          value: "5"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
